import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import { StrictMode } from 'react';
import { CurrencyProvider } from './Context/CurrencyContext'; // Ensure this path is correct

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <StrictMode>
          <CurrencyProvider>{children}</CurrencyProvider>
        </StrictMode>
      </body>
    </html>
  );
}
